### ISSUE TITLE
Version 1.7.7 does not start

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.ping#187]
Adapter stays "red", log says
`<html><body>

ping.0 | 2024-09-28 17:27:50.678 | error | Cannot read properties of undefined (reading 'init')
-- | -- | -- | --
ping.0 | 2024-09-28 17:27:50.677 | error | TypeError:  Cannot read properties of undefined (reading 'init')    at main  (/opt/iobroker/node_modules/iobroker.ping/main.js:858:16)
ping.0 | 2024-09-28 17:27:50.672 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'init')
ping.0 | 2024-09-28 17:27:50.670 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
host.iobroker | 2024-09-28 17:27:18.810 | error | instance system.adapter.ping.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2024-09-28 17:27:18.809 | error | Caught by controller[1]:     at main (/opt/iobroker/node_modules/iobroker.ping/main.js:858:16)
host.iobroker | 2024-09-28 17:27:18.809 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'init')
host.iobroker | 2024-09-28 17:27:18.809 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:

</body>
</html>

iobroker on proxmox HA with one Master and 2 Slaves, Beta repository `
I went back to 1.7.6 which runs without any issues.
js-controller 6.0.11
node.js 20.17.0
Proxmox/Debian12 Container

**Comment by dimaiv7** [comment]
same for me

**Comment by xMFPx** [comment]
same @ my system

**Comment by diamand2k22** [comment]
for me also the same, adapter does not start

**Comment by sammie76-2** [comment]
Same here, there are restart loops.

**Comment by fuchs-1978** [comment]
Same here

**Comment by GermanBluefox** [comment]
Please test 1.7.8

**Comment by mattreim** [comment]
It's the same behavior.

**Comment by sjfm-design** [comment]
1.7.8 restart loop dedectet.
back to 1.7.6, ok.

**Comment by fuchs-1978** [comment]
1.7.8 Same here

**Comment by Ilovegym66** [comment]
1.7.8 don't start, uncaught exception debug log:
`
2024-09-29 07:35:22.790  - info: host.iobroker instance system.adapter.ping.0 in version "1.7.8" started with pid 23644
2024-09-29 07:35:23.431  - debug: ping.0 (23644) Redis Objects: Use Redis connection: 10.10.2.10:6379
2024-09-29 07:35:23.445  - debug: ping.0 (23644) Objects client ready ... initialize now
2024-09-29 07:35:23.447  - debug: ping.0 (23644) Objects create System PubSub Client
2024-09-29 07:35:23.448  - debug: ping.0 (23644) Objects create User PubSub Client
2024-09-29 07:35:23.653  - debug: ping.0 (23644) Objects client initialize lua scripts
2024-09-29 07:35:23.659  - debug: ping.0 (23644) Objects connected to redis: 10.10.2.10:6379
2024-09-29 07:35:23.673  - debug: ping.0 (23644) Redis States: Use Redis connection: 10.10.2.10:6379
2024-09-29 07:35:23.677  - debug: ping.0 (23644) States create System PubSub Client
2024-09-29 07:35:23.678  - debug: ping.0 (23644) States create User PubSub Client
2024-09-29 07:35:23.692  - debug: ping.0 (23644) States connected to redis: 10.10.2.10:6379
2024-09-29 07:35:23.730  - debug: ping.0 (23644) Plugin sentry Initialize Plugin (enabled=true)
2024-09-29 07:35:24.165  - info: tr-064.0 (9792) {"NewTotalNumberSyncGroups":"2","NewSyncGroupName":"sync_dsl","NewSyncGroupMode":"VDSL","Newmax_ds":"12191250","Newmax_us":"5185625","Newds_current_bps":"18787,35340,24388,25714,49952,22485,20304,32760,27299,23608,27126,27069,33018,39308,20821,28397,19679,30771,31506,28071","Newmc_current_bps":"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","Newus_current_bps":"4155,20147,23576,6363,12847,11059,3890,6055,6003,5911,32086,5945,6549,12891,5409,7919,4254,54602,6481,4300","Newprio_realtime_bps":"1885,9685,21370,2739,10365,8006,1832,3309,4235,3772,27614,3673,4375,6384,3185,2735,2722,50886,2856,2016","Newprio_high_bps":"1041,1077,1088,958,1214,911,1024,1066,936,1136,1132,1047,977,1169,926,1111,929,1082,1001,1073","Newprio_default_bps":"1229,9385,1118,2666,1268,2142,1034,1680,832,1003,3340,1225,1197,5338,1298,4073,603,2634,2624,1211","Newprio_low_bps":"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"}
2024-09-29 07:35:24.603  - info: ping.0 (23644) starting. Version 1.7.8 in /opt/iobroker/node_modules/iobroker.ping, node: v20.17.0, js-controller: 6.0.11
2024-09-29 07:35:24.749  - error: ping.0 (23644) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-09-29 07:35:24.750  - error: ping.0 (23644) unhandled promise rejection: Cannot read properties of undefined (reading 'init')
2024-09-29 07:35:24.752  - error: ping.0 (23644) TypeError: Cannot read properties of undefined (reading 'init')
    at main (/opt/iobroker/node_modules/iobroker.ping/main.js:858:16)
2024-09-29 07:35:24.753  - error: ping.0 (23644) Cannot read properties of undefined (reading 'init')
2024-09-29 07:35:25.266  - info: ping.0 (23644) terminating
2024-09-29 07:35:25.267  - debug: ping.0 (23644) Plugin sentry destroyed
2024-09-29 07:35:25.267  - warn: ping.0 (23644) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-09-29 07:35:25.546  - info: web.0 (13011) ==> Connected system.user.admin from 10.1.1.44
2024-09-29 07:35:25.802  - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-09-29 07:35:25.802  - error: host.iobroker Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'init')
2024-09-29 07:35:25.802  - error: host.iobroker Caught by controller[1]:     at main (/opt/iobroker/node_modules/iobroker.ping/main.js:858:16)
2024-09-29 07:35:25.802  - error: host.iobroker instance system.adapter.ping.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-09-29 07:35:25.802  - info: host.iobroker Restart adapter system.adapter.ping.0 because enabled
2024-09-29 07:35:25.802  - warn: host.iobroker Do not restart adapter system.adapter.ping.0 because restart loop detected
2024-09-29 07:35:25.817  - info: notification-manager.0 (17643) Send notification "system.restartLoop" to "email.0"
2024-09-29 07:35:25.830  - info: email.0 (1834) New notification received from system.adapter.notification-manager.0

`
System: Buanet Docker V10, Admin 7.1.5, JS-Controller 6.0.11

**Comment by dimaiv7** [comment]
1.7.8 don't start

**Comment by mcm1957** [comment]
Issue replaced by #188 (but not solved yet).
